# File to create a conda environment with all necessary dependencies.
# To create a new conda environment with the dependencies listed in this file, run:
# `conda env create -f environment.yml`
#
# If this file changes, update the environment (has to be activated) with:
# `conda env update --file environment.yml --prune`


dependencies:
  - conda-forge::pip=21.0.1
#  - conda-forge::python=3.9.16 # where did this come from?
  - pip:
#      - matplotlib==3.4.3
      - matplotlib==3.6.2

  - python==3.9
  - numpy==1.25
  - pandas
  - scipy
  - cmocean
  - astropy==5.3.3
  - jupyterlab==4.0.5
#  - pickle
#  - pandas=1.4
#  - matplotlib==3.4.3
#  - scipy>=1.8
  - seaborn>=0.12
#  - cmocean==2.0
#  - pickle=4.0
#  - corner

##  Bioverse requires a few packages:
  - dynesty=1.1
  - emcee=3.1.1

# install Bioverse:
  - pip:
#    - git+https://github.com/danielapai/bioverse@v1.1.1
#    - git+https://github.com/danielapai/bioverse@develop
    - -e /Users/schlecker/repos/bioverse